### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/zig#21]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/zig/issues/12)
- [x] [Add key features](https://github.com/exercism/zig/issues/13)
- [x] [Add tags](https://github.com/exercism/zig/issues/14)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/zig/issues/15)
- [x] [Update status of track](https://github.com/exercism/zig/issues/19)
- [x] [Update status of Concept Exercises](https://github.com/exercism/zig/issues/20)
- [x] [Pass linting checks](https://github.com/exercism/zig/issues/16)
- [x] [Build Test Runner](https://github.com/exercism/zig/issues/17)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/zig/issues/18) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by massivelivefun** [comment]
The track's descriptive tags have been added to the repo's config.json file.

Please refer to this issue below:
#14

**Comment by ErikSchierboom** [comment]
I've gone through the updated [New track docs](https://exercism.org/docs/building/tracks/new) and I think we're in a good enough state to consider launching!

- Exercises implemented: 19 (we could do with some more, but this is good enough to start with)
- config.json: looks good too
- Docs: all seem to be fine
- Test runner: v1 test runner working and reasonably fast
- Lines of code counter: [Zig is supported](https://github.com/XAMPPRocky/tokei/blob/master/languages.json)
- Highlightjs: opened a PR: https://github.com/exercism/website/pull/3445

I think the main things to focus on is:

- Adding more exercises
- Configuring the snippet extractor: https://github.com/exercism/snippet-extractor/

Having a codemirror plugin for Zig would be lovely, but that's admittedly a bit more work.

A representer would also be good to build once there is a fair number of students.
Same goes for an analyzer.

@massivelivefun @hiljusti @ee7 Anything I've missed?

**Comment by hiljusti** [comment]
I'm excited to see the progress that's happened here!

I think it's in a good state for launch as well, and hopefully that leads to more interest, more contributors, etc. Let's start the positive feedback loop

**Comment by ErikSchierboom** [comment]
@hiljusti Want to have the honor to do the PR to set `active` to `true` in the `config.json`?

**Comment by ErikSchierboom** [comment]
I don't mind. I think it is good to have a track maintainer merge the PR though.

**Comment by hiljusti** [comment]
It's working!

**Comment by ErikSchierboom** [comment]
Yay!
